# -*- coding: utf-8 -*-
"""ML_HW6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10lHBPFoNhTiiPe-yZ7SwAV1wwrkGc4En

# Homework 6 - Generative Adversarial Network
This is the sample code for hw6 of 2022 Machine Learning course in National Taiwan University. 

In this sample code, there are 5 sections:
1. Environment setting
2. Dataset preparation
3. Model setting
4. Train
5. Inference

Your goal is to do anime face generation, if you have any question, please discuss at NTU COOL

# Environment setting
In this section, we will prepare for the dataset and set some environment variable

## Download Dataset
"""

# get dataset from huggingface hub
# !curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
# !apt-get install git-lfs
# !git lfs install
# !git clone https://huggingface.co/datasets/LeoFeng/MLHW_6
# !unzip ./MLHW_6/faces.zip -d .

"""## Other setting"""

import os
from config import *
import utils
from trainer_gan import TrainerGAN


utils.same_seeds(2022)


"""## Show the image
Show some sample in the dataset
"""

temp_dataset = utils.get_dataset(os.path.join(workspace_dir, 'faces'))

# images = [temp_dataset[i] for i in range(4)]
# grid_img = torchvision.utils.make_grid(images, nrow=4)
# plt.figure(figsize=(10,10))
# plt.imshow(grid_img.permute(1, 2, 0))
# plt.show()

"""# Model setting
In this section, we will create models and trainer.

## Create model
In this section, we will create models for Generator and Discriminator
"""

"""# Train
In this section, we will first set the config for trainer, then use it to train generator and discriminator

## Set config
"""

"""## Start to train"""
# only work on debug run with pycharm
trainer = TrainerGAN(config)
trainer.train()
